server:
  port: 9000
spring:
    profiles:
        active: development

    thymeleaf:
        cache: false

    jade4j:
        caching: false

    dataSource:
      type: org.apache.tomcat.jdbc.pool.DataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost/uar
      username: root
      password: 123456

    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      hbm2ddl.auto: update
      show_sql: false

    redis:
      host: localhost
      port: 6379
      default_expire_time: 86400

jtang:
    url: http://120.27.7.132:8080/SeGA