server:
  port: 9000
spring:
    profiles:
        active: development

    thymeleaf:
        cache: false

    jade4j:
        caching: false

    dataSource:
      mysql:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://rm-2zetv12ybvdbxmro4o.mysql.rds.aliyuncs.com/uar
        username: sega_tester
        password: sega_tester123

    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      hbm2ddl.auto: update
      show_sql: false

    redis:
      host: localhost
      port: 6379
      default_expire_time: 86400

jtang:
    url: http://120.27.7.132:8080/SeGA