server:
  port: 9000
spring:
    profiles:
        active: development

    thymeleaf:
        cache: false

    jade4j:
        caching: false

    dataSource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1/uar
      username: sega
      password: sega

    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      hbm2ddl.auto: update
      show_sql: false

    redis:
      host: localhost
      port: 6379
      default_expire_time: 86400

jtang:
    url: http://120.24.49.253:8080/SeGA